[llm.agent]
model = "openrouter/google/gemini-3-flash-preview"
base_url = "https://openrouter.ai/api/v1"
api_key = ""
max_output_tokens = 16384


[llm.env]
model = "openrouter/google/gemini-3-flash-preview"
base_url = "https://openrouter.ai/api/v1"
api_key = ""
max_output_tokens = 16384